name: infotainment_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  retrofit: ^4.0.1
  dio: ^5.3.3
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  go_router: ^13.2.0
  sliver_tools: ^0.2.12
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.10+1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: CorporateABQ
      fonts:
        - asset: assets/fonts/Corporate_A_BQ/bold.ttf
          weight: 700
        - asset: assets/fonts/Corporate_A_BQ/medium.ttf
          weight: 500
        - asset: assets/fonts/Corporate_A_BQ/regular.ttf
        - asset: assets/fonts/Corporate_A_BQ/light.ttf
          weight: 300
    - family: MBCorpoSTitle
      fonts:
        - asset: assets/fonts/MB_Corpo_S_Title/regular.otf

flutter_gen:
  output: lib/generated/

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
