name: infotainment_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  retrofit: ^4.0.1
  dio: ^5.3.3
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  go_router: ^13.2.0
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/generated/

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
